### PR TITLE
Fix #21 and Green for Inline DD

### LINKED ISSUE #21: IF THEN Over Multiple Lines Color is Inccorect
`//` are light blue but  should be yellow like other labels 
image

### PR DESCRIPTION
**Pull request by dkelosky**
@tjohnsonBCM, what do you think of green for inline DD?
image

Not opposed to orange / string color still, but this is another option.

### CODE REVIEW

**Comment by ghost** [comment]
@dkelosky Not opposed to the green color. IMO the scope name should be determined based on JCL semantics, more than color preferences. According to Sublime Text doc:
> Strings that used unconventional quotes, such as < and > with C imports, should use `string.quoted.other`

Perhaps the `*` and `/*` that surround an inline DD can be considered as a form of "unconventional quotes". I think it makes sense to compare an inline DD to a string, as JCL does not parse the contents (except it inserts symbols when `SYMBOLS=JCLONLY` is used, similar to string interpolation with backticks in JavaScript like <code>&#96;Hello ${name}&#96;</code>).

Regarding `entity.name.type`, Sublime Text says:
> The entity scopes are generally assigned to the names of data structures, types and other uniquely-identifiable constructs in code and markup.

I don't believe an inline DD is a data structure or type, but it probably qualifies as a "uniquely-identifiable construct". Perhaps it is desirable to use a different category of scope to better distinguish inline DDs from single-quoted JCL strings.

I think a good argument can be made for either of these scope names, so I'd suggest using whichever scope name seems most semantically correct to you for JCL 😄

**Comment by dkelosky** [comment]
Hmm, good points, mostly I picked based on colors 😎

Instream DDs usually contain source code (C source for example), control statements (like how things are linked together), or parameters (like compiler options).

I'll read up and see more what the names mean, I've only learned this grammar stuff recently 😀

Probably should take a look at all names being used...

**Comment by dkelosky** [comment]
Also the semantic highlighting might help get more distinguishing colors with proper names but it has some drawbacks

**Comment by ghost** [comment]
> Also the semantic highlighting might help get more distinguishing colors with proper names but it has some drawbacks

Sorry if my usage of the word "semantic" was confusing. I didn't mean to imply that "semantic highlighting" is needed, as the Textmate grammar seems to work fine 😃

**Comment by dkelosky** [comment]
It wasn't confusing; I was conflating things a bit 😄.  I think a primary goal would be to use semantically correct names for JCL tokens.  Secondly, I was observing that semantic highlighting allows for more customization with modifiers and user tailoring might give a better experience.

**Pull request merged**
